name: Production

on:
  push:
    tags: v[0-9]+\.[0-9]+\.[0-9]+
    
jobs:
  test:
    name: test
    runs-on: [self-hosted, dev]

    steps:
    - uses: actions/checkout@v3
    - name: Enter Folder application
      run: cd c:/actions-runner/work/minimal-api/minimal-api
    - name: Build
      run: dotnet build minimal-api 
    - name: Run tests
      run: dotnet test

  deploy:
    name: deploy
    runs-on: [self-hosted, prod]
    needs: [test]

    steps:
    - uses: actions/checkout@v3
    - name: Enter Folder application
      run: cd c:/action-runner-prod/work/minimal-api/minimal-api
    - name: Build
      run: dotnet build minimal-api -c Release 
    - name: Publish application
      run: dotnet publish -c Release
    - name: Enter published folder
      run: cd c:/action-runner-prod/work/minimal-api/minimal-api/bin/Release/net6.0/publish
    - name: Start Application
      run: dotnet minimal-api.dll
